sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 7.2

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 7.3
      env: WP_VERSION=latest WPSNIFF=1

before_script:
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini
  - composer global require wp-coding-standards/wpcs dealerdirect/phpcodesniffer-composer-installer

script:
  - if [[ "$WPSNIFF" == "1" ]]; then phpcs --standard=phpcs.ruleset.xml --extensions=php .; fi
